apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: jftiano/udagram-api-feed
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "1Gi"
            cpu: "1024m"
          limits:
            memory: "2Gi"
            cpu: "1024m"
        envFrom:
          - configMapRef:
              name: env-config